---
os_auth_url:  "{{ lookup('env','OS_AUTH_URL') }}" 
os_tenant_name: "{{ lookup('env','OS_TENANT_NAME') }}" 
os_username: "{{ lookup('env','OS_USERNAME') }}"
os_password:  "{{ lookup('env','OS_PASSWORD') }}"
